repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=79]      
-   repo:  https://github.com/pycqa/flake8
    rev: stable
    hooks:
    - id: flake8

